# Generated by Django 3.2 on 2021-05-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solver', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sum',
        ),
    ]
